apiVersion: v1
data:
  RemoteSettingsUrl: <Base64 encoded settings url>
  # http://settings.common.svc.cluster.local/sirius/brokerage
kind: Secret
metadata:
  name: brokerage
  namespace: sirius
type: Opaque
